### ISSUE TITLE
General interface for ropensci class

### ISSUE THREAD

**Issue by sckott** [ropensci-archive/ropensciToolkit#3]
@ropensci/owners 

Seems like there are two ways to do this:
1. Have a `print` method for the `ropensci` class, then when someone uses one of our functions in any of our packages, the output will be whatever is defined in the print method. However, do we not want the printing or ropensci class information to "step on the toes" of the particular package/function the user is using?
2. Have functions that do `print`/`summary`/etc. stuff on the `ropensci` class, but make them generic methods on the `ropensci` class new functions so that a user has to specifically call them, so that the output of the function they called is whatever the default output is for that fxn. 

Which is better? Thoughts?

Right now, we have it set up for the first option, and within a function I assign the `ropensci` class along with any class that is assigned by the function itself.

**Comment by karthik** [comment]
I like the idea of a `print`method. I love the prototype you posted. Exactly the vision I had when writing the original proposal. It would be general enough to extend to most of our packages. I'm a little more worried about `summary` though. It's not easily generalizable and will require special handling for each package. That alone may not be worth it. We could just incorporate a summary method into each package and leave this one here.

**Comment by sckott** [comment]
> Exactly the vision I had when writing the original proposal.

Yeah, just used what you had, and tried to finish it off. 

So the main thing I'm trying to get at here is whether or not we want the output of `print.ropensci` to be the default output for all functions that output objects that have class `ropensci` (in addition to any other classes)? If an object outputting from a function has class `ropensci`, and there is a print method for it, then they will get something like 

``` coffee
Call status  :  success: (200) OK 
Results from :  www.ncdc.noaa.gov 
Date/time    :  Fri, 29 Nov 2013 23:53:16 GMT 
Data format  :  data.frame 
Queried      :  
 datasetid = GHCND 
 locationid = FIPS:02 
 startdate = 2010-05-01 
 enddate = 2010-05-31 
 limit = 5 
            station value attributes datatype       date
1 GHCND:CA001206197     0      T,,G,     PRCP 2010-05-01
2 GHCND:CA001206197     0       ,,G,     SNOW 2010-05-01
3 GHCND:CA001206197     0       ,,G,     SNWD 2010-05-01
4 GHCND:CA001206197    80       ,,G,     TMAX 2010-05-01
5 GHCND:CA001206197     5       ,,G,     TMIN 2010-05-01
```

Is this what we want?  Or do we want to make a method like `print_ro` that the user has to explicitly call to get the above output, e.g. `print_ro(output)`?

**Comment by cboettig** [comment]
@ropensci/owners 

Not sure I follow here, but it sounds like you are actually talking about what metadata we want each function to return.  That is, from the example above, I get the idea that every function would include `Call status`, `Results from`, `Date/time`, etc etc.  

Worrying about how this information is printed to the screen is putting the cart before the horse, in my opinion.  Looking at the [code](https://github.com/ropensci/ropensciToolkit/blob/master/R/summary.ropensci.r) perhaps you've already defined this set of metadata in whatever the object `d` is?  Seems to be a combination of some output metadata and some of the httr::response class slots?  

Once we have a generic definition for the return object, defining print/summary methods etc should be easy.  Besides, I feel the real power in having such an object is not sharing print/summary methods, but more easily being able to combine it with data coming from another ropensci package.  

Without defining such an object I'm not clear how we go forward defining the methods in this package.  Obviously we would do well to build on existing metadata standards here rather than re-invent the wheel.  (That could be EML, or stricter and more ambitious could be entirely RDF, or something else).  

Sorry if I'm missing the point entirely -- please set me straight.

**Comment by sckott** [comment]
I think there are two things this package should do:
- Methods for printing diagnostics and summaries of output objects that is general across our packages, and 
- Providing tools that make integrating our packages easier 

We haven't worked on the latter as of yet in the pkg. Both seem important in my opinion. The first seems much easier to do, while the second will be much harder. 

wrt tools to integrate packages, can we start to lay out what we want?  What do we want in this general object, and what format should it take (EML, RDF, just a list of stuff).
